### ISSUE TITLE
How to report conversion problem?

### ISSUE THREAD

**Issue by iapyeh** [hexenq/kuroshiro.js#10]
The kuroshiro.js is an excellent project. Thank you for this great work. Sometime, I encountered tiny issues. For example, "五輪(ごりん)"  is converted to "いつわ". I'd like to know how to report this kind of issues, so that eventually we have a more and more perfect kuroshiro.js?

**Comment by hexenq** [comment]
Hello, iapyeh. Thanks for using kuroshiro.js. Considering your issue, I have updated [the dict files](https://github.com/hexenq/kuroshiro.js/tree/master/dist/dict) according to kuromoji.js which this project depends on. And it may solve part of your issue (e.g. the "五輪" case). 

In addition, you can compile and use a suitable IPA dictionary instead of the default one. (This would be a tough work though...)

By the way, your issue seems to have certain association with morphological analyzation. However, kuroshiro.js mainly focuses on the processing of the results of morphological analyzation while one of the dependency of kuroshiro.js — kuromoji is in charge of morphological analyzation. Therefore at this stage, I could not give you more suggestions. I'm sorry for that. Hope we can find a workaround.😃

**Comment by iapyeh** [comment]
Thank you very much, it works. By the way, I found another kind of issue different from the above one, like this:
![image](https://cloud.githubusercontent.com/assets/4695577/26750261/87321816-4850-11e7-87f2-8663b8cbc51e.png)
(the position "しろ" in the furigana of "面白い言葉")

**Comment by hexenq** [comment]
Hello iapyeh. I have fixed the bug you mentioned above and published a new version of kuroshiro.js (0.1.5). Have a check. I'll close this issue. Feel free to raise a new issue if you have further more questions.
