### ISSUE TITLE
[Firefox/Safari when website deployed] RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer

### ISSUE THREAD

**Issue by mornir** [hexenq/kuroshiro.js#30]
Hi! 

I created a very basic website with Vue and kuroshiro:
https://github.com/mornir/kuroshiro-test

I deployed this website on Netlify:
https://cranky-sammet-85b234.netlify.com/

When I visite this website, I get the following error on Firefox and Safari:
`RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer`

It works fine in Chrome and Edge.

My team was about to use kuroshiro in production, but we need support for Firefox and Safari 😕

**Comment by hexenq** [comment]
Hello, mornir. I tried and failed with Netlify. But after that I ran your test with local server on Firefox 60.0.1 (64bit) and it showed all ok. I think we could try to figure out what's different between Netlify and local server, and the difference between Chrome-Edge and Firefox-Safari in order to find the solution. What if deploy your app elsewhere or locally?

**Comment by mornir** [comment]
Thanks for the quick reply 😃
Yes, it also works fine locally on my side. This behavior is really weird...
I tried using surge, and it seems to work fine:
http://attractive-clover.surge.sh/

**Comment by mornir** [comment]
Since it seems related to Netlify, I'm closing this issue.
